# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/francisco/Escritorio/TFG-Enviroment/Ripes

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/francisco/Escritorio/TFG-Enviroment/Ripes

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/francisco/Escritorio/TFG-Enviroment/Ripes/CMakeFiles /home/francisco/Escritorio/TFG-Enviroment/Ripes/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/francisco/Escritorio/TFG-Enviroment/Ripes/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Ripes

# Build rule for target.
Ripes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Ripes
.PHONY : Ripes

# fast build rule for target.
Ripes/fast:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/build
.PHONY : Ripes/fast

#=============================================================================
# Target rules for targets named Ripes_autogen

# Build rule for target.
Ripes_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Ripes_autogen
.PHONY : Ripes_autogen

# fast build rule for target.
Ripes_autogen/fast:
	$(MAKE) -f CMakeFiles/Ripes_autogen.dir/build.make CMakeFiles/Ripes_autogen.dir/build
.PHONY : Ripes_autogen/fast

#=============================================================================
# Target rules for targets named fancytabbar_lib

# Build rule for target.
fancytabbar_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fancytabbar_lib
.PHONY : fancytabbar_lib

# fast build rule for target.
fancytabbar_lib/fast:
	$(MAKE) -f external/fancytabbar/CMakeFiles/fancytabbar_lib.dir/build.make external/fancytabbar/CMakeFiles/fancytabbar_lib.dir/build
.PHONY : fancytabbar_lib/fast

#=============================================================================
# Target rules for targets named fancytabbar_lib_autogen

# Build rule for target.
fancytabbar_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fancytabbar_lib_autogen
.PHONY : fancytabbar_lib_autogen

# fast build rule for target.
fancytabbar_lib_autogen/fast:
	$(MAKE) -f external/fancytabbar/CMakeFiles/fancytabbar_lib_autogen.dir/build.make external/fancytabbar/CMakeFiles/fancytabbar_lib_autogen.dir/build
.PHONY : fancytabbar_lib_autogen/fast

#=============================================================================
# Target rules for targets named VSRTL

# Build rule for target.
VSRTL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VSRTL
.PHONY : VSRTL

# fast build rule for target.
VSRTL/fast:
	$(MAKE) -f external/VSRTL/CMakeFiles/VSRTL.dir/build.make external/VSRTL/CMakeFiles/VSRTL.dir/build
.PHONY : VSRTL/fast

#=============================================================================
# Target rules for targets named VSRTL_autogen

# Build rule for target.
VSRTL_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VSRTL_autogen
.PHONY : VSRTL_autogen

# fast build rule for target.
VSRTL_autogen/fast:
	$(MAKE) -f external/VSRTL/CMakeFiles/VSRTL_autogen.dir/build.make external/VSRTL/CMakeFiles/VSRTL_autogen.dir/build
.PHONY : VSRTL_autogen/fast

#=============================================================================
# Target rules for targets named vsrtl_int_lib

# Build rule for target.
vsrtl_int_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vsrtl_int_lib
.PHONY : vsrtl_int_lib

# fast build rule for target.
vsrtl_int_lib/fast:
	$(MAKE) -f external/VSRTL/interface/CMakeFiles/vsrtl_int_lib.dir/build.make external/VSRTL/interface/CMakeFiles/vsrtl_int_lib.dir/build
.PHONY : vsrtl_int_lib/fast

#=============================================================================
# Target rules for targets named vsrtl_int_lib_autogen

# Build rule for target.
vsrtl_int_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vsrtl_int_lib_autogen
.PHONY : vsrtl_int_lib_autogen

# fast build rule for target.
vsrtl_int_lib_autogen/fast:
	$(MAKE) -f external/VSRTL/interface/CMakeFiles/vsrtl_int_lib_autogen.dir/build.make external/VSRTL/interface/CMakeFiles/vsrtl_int_lib_autogen.dir/build
.PHONY : vsrtl_int_lib_autogen/fast

#=============================================================================
# Target rules for targets named vsrtl_core_lib

# Build rule for target.
vsrtl_core_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vsrtl_core_lib
.PHONY : vsrtl_core_lib

# fast build rule for target.
vsrtl_core_lib/fast:
	$(MAKE) -f external/VSRTL/core/CMakeFiles/vsrtl_core_lib.dir/build.make external/VSRTL/core/CMakeFiles/vsrtl_core_lib.dir/build
.PHONY : vsrtl_core_lib/fast

#=============================================================================
# Target rules for targets named vsrtl_core_lib_autogen

# Build rule for target.
vsrtl_core_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vsrtl_core_lib_autogen
.PHONY : vsrtl_core_lib_autogen

# fast build rule for target.
vsrtl_core_lib_autogen/fast:
	$(MAKE) -f external/VSRTL/core/CMakeFiles/vsrtl_core_lib_autogen.dir/build.make external/VSRTL/core/CMakeFiles/vsrtl_core_lib_autogen.dir/build
.PHONY : vsrtl_core_lib_autogen/fast

#=============================================================================
# Target rules for targets named vsrtl_gfx_lib

# Build rule for target.
vsrtl_gfx_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vsrtl_gfx_lib
.PHONY : vsrtl_gfx_lib

# fast build rule for target.
vsrtl_gfx_lib/fast:
	$(MAKE) -f external/VSRTL/graphics/CMakeFiles/vsrtl_gfx_lib.dir/build.make external/VSRTL/graphics/CMakeFiles/vsrtl_gfx_lib.dir/build
.PHONY : vsrtl_gfx_lib/fast

#=============================================================================
# Target rules for targets named vsrtl_gfx_lib_autogen

# Build rule for target.
vsrtl_gfx_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vsrtl_gfx_lib_autogen
.PHONY : vsrtl_gfx_lib_autogen

# fast build rule for target.
vsrtl_gfx_lib_autogen/fast:
	$(MAKE) -f external/VSRTL/graphics/CMakeFiles/vsrtl_gfx_lib_autogen.dir/build.make external/VSRTL/graphics/CMakeFiles/vsrtl_gfx_lib_autogen.dir/build
.PHONY : vsrtl_gfx_lib_autogen/fast

#=============================================================================
# Target rules for targets named vsrtl_cmp_lib

# Build rule for target.
vsrtl_cmp_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vsrtl_cmp_lib
.PHONY : vsrtl_cmp_lib

# fast build rule for target.
vsrtl_cmp_lib/fast:
	$(MAKE) -f external/VSRTL/components/CMakeFiles/vsrtl_cmp_lib.dir/build.make external/VSRTL/components/CMakeFiles/vsrtl_cmp_lib.dir/build
.PHONY : vsrtl_cmp_lib/fast

#=============================================================================
# Target rules for targets named vsrtl_cmp_lib_autogen

# Build rule for target.
vsrtl_cmp_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vsrtl_cmp_lib_autogen
.PHONY : vsrtl_cmp_lib_autogen

# fast build rule for target.
vsrtl_cmp_lib_autogen/fast:
	$(MAKE) -f external/VSRTL/components/CMakeFiles/vsrtl_cmp_lib_autogen.dir/build.make external/VSRTL/components/CMakeFiles/vsrtl_cmp_lib_autogen.dir/build
.PHONY : vsrtl_cmp_lib_autogen/fast

#=============================================================================
# Target rules for targets named SingleCycleLeros

# Build rule for target.
SingleCycleLeros: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SingleCycleLeros
.PHONY : SingleCycleLeros

# fast build rule for target.
SingleCycleLeros/fast:
	$(MAKE) -f external/VSRTL/components/Leros/SingleCycleLeros/CMakeFiles/SingleCycleLeros.dir/build.make external/VSRTL/components/Leros/SingleCycleLeros/CMakeFiles/SingleCycleLeros.dir/build
.PHONY : SingleCycleLeros/fast

#=============================================================================
# Target rules for targets named SingleCycleLeros_autogen

# Build rule for target.
SingleCycleLeros_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SingleCycleLeros_autogen
.PHONY : SingleCycleLeros_autogen

# fast build rule for target.
SingleCycleLeros_autogen/fast:
	$(MAKE) -f external/VSRTL/components/Leros/SingleCycleLeros/CMakeFiles/SingleCycleLeros_autogen.dir/build.make external/VSRTL/components/Leros/SingleCycleLeros/CMakeFiles/SingleCycleLeros_autogen.dir/build
.PHONY : SingleCycleLeros_autogen/fast

#=============================================================================
# Target rules for targets named tst_nestedcomponent

# Build rule for target.
tst_nestedcomponent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_nestedcomponent
.PHONY : tst_nestedcomponent

# fast build rule for target.
tst_nestedcomponent/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_nestedcomponent.dir/build.make external/VSRTL/test/CMakeFiles/tst_nestedcomponent.dir/build
.PHONY : tst_nestedcomponent/fast

#=============================================================================
# Target rules for targets named tst_leros

# Build rule for target.
tst_leros: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_leros
.PHONY : tst_leros

# fast build rule for target.
tst_leros/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_leros.dir/build.make external/VSRTL/test/CMakeFiles/tst_leros.dir/build
.PHONY : tst_leros/fast

#=============================================================================
# Target rules for targets named tst_adderandreg

# Build rule for target.
tst_adderandreg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_adderandreg
.PHONY : tst_adderandreg

# fast build rule for target.
tst_adderandreg/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_adderandreg.dir/build.make external/VSRTL/test/CMakeFiles/tst_adderandreg.dir/build
.PHONY : tst_adderandreg/fast

#=============================================================================
# Target rules for targets named tst_counter

# Build rule for target.
tst_counter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_counter
.PHONY : tst_counter

# fast build rule for target.
tst_counter/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_counter.dir/build.make external/VSRTL/test/CMakeFiles/tst_counter.dir/build
.PHONY : tst_counter/fast

#=============================================================================
# Target rules for targets named tst_rannumgen

# Build rule for target.
tst_rannumgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_rannumgen
.PHONY : tst_rannumgen

# fast build rule for target.
tst_rannumgen/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_rannumgen.dir/build.make external/VSRTL/test/CMakeFiles/tst_rannumgen.dir/build
.PHONY : tst_rannumgen/fast

#=============================================================================
# Target rules for targets named tst_enumandmux

# Build rule for target.
tst_enumandmux: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_enumandmux
.PHONY : tst_enumandmux

# fast build rule for target.
tst_enumandmux/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_enumandmux.dir/build.make external/VSRTL/test/CMakeFiles/tst_enumandmux.dir/build
.PHONY : tst_enumandmux/fast

#=============================================================================
# Target rules for targets named tst_aluandreg

# Build rule for target.
tst_aluandreg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_aluandreg
.PHONY : tst_aluandreg

# fast build rule for target.
tst_aluandreg/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_aluandreg.dir/build.make external/VSRTL/test/CMakeFiles/tst_aluandreg.dir/build
.PHONY : tst_aluandreg/fast

#=============================================================================
# Target rules for targets named tst_registerfile

# Build rule for target.
tst_registerfile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_registerfile
.PHONY : tst_registerfile

# fast build rule for target.
tst_registerfile/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_registerfile.dir/build.make external/VSRTL/test/CMakeFiles/tst_registerfile.dir/build
.PHONY : tst_registerfile/fast

#=============================================================================
# Target rules for targets named tst_memory

# Build rule for target.
tst_memory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_memory
.PHONY : tst_memory

# fast build rule for target.
tst_memory/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_memory.dir/build.make external/VSRTL/test/CMakeFiles/tst_memory.dir/build
.PHONY : tst_memory/fast

#=============================================================================
# Target rules for targets named tst_nestedcomponent_autogen

# Build rule for target.
tst_nestedcomponent_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_nestedcomponent_autogen
.PHONY : tst_nestedcomponent_autogen

# fast build rule for target.
tst_nestedcomponent_autogen/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_nestedcomponent_autogen.dir/build.make external/VSRTL/test/CMakeFiles/tst_nestedcomponent_autogen.dir/build
.PHONY : tst_nestedcomponent_autogen/fast

#=============================================================================
# Target rules for targets named tst_leros_autogen

# Build rule for target.
tst_leros_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_leros_autogen
.PHONY : tst_leros_autogen

# fast build rule for target.
tst_leros_autogen/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_leros_autogen.dir/build.make external/VSRTL/test/CMakeFiles/tst_leros_autogen.dir/build
.PHONY : tst_leros_autogen/fast

#=============================================================================
# Target rules for targets named tst_adderandreg_autogen

# Build rule for target.
tst_adderandreg_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_adderandreg_autogen
.PHONY : tst_adderandreg_autogen

# fast build rule for target.
tst_adderandreg_autogen/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_adderandreg_autogen.dir/build.make external/VSRTL/test/CMakeFiles/tst_adderandreg_autogen.dir/build
.PHONY : tst_adderandreg_autogen/fast

#=============================================================================
# Target rules for targets named tst_counter_autogen

# Build rule for target.
tst_counter_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_counter_autogen
.PHONY : tst_counter_autogen

# fast build rule for target.
tst_counter_autogen/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_counter_autogen.dir/build.make external/VSRTL/test/CMakeFiles/tst_counter_autogen.dir/build
.PHONY : tst_counter_autogen/fast

#=============================================================================
# Target rules for targets named tst_rannumgen_autogen

# Build rule for target.
tst_rannumgen_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_rannumgen_autogen
.PHONY : tst_rannumgen_autogen

# fast build rule for target.
tst_rannumgen_autogen/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_rannumgen_autogen.dir/build.make external/VSRTL/test/CMakeFiles/tst_rannumgen_autogen.dir/build
.PHONY : tst_rannumgen_autogen/fast

#=============================================================================
# Target rules for targets named tst_enumandmux_autogen

# Build rule for target.
tst_enumandmux_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_enumandmux_autogen
.PHONY : tst_enumandmux_autogen

# fast build rule for target.
tst_enumandmux_autogen/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_enumandmux_autogen.dir/build.make external/VSRTL/test/CMakeFiles/tst_enumandmux_autogen.dir/build
.PHONY : tst_enumandmux_autogen/fast

#=============================================================================
# Target rules for targets named tst_aluandreg_autogen

# Build rule for target.
tst_aluandreg_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_aluandreg_autogen
.PHONY : tst_aluandreg_autogen

# fast build rule for target.
tst_aluandreg_autogen/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_aluandreg_autogen.dir/build.make external/VSRTL/test/CMakeFiles/tst_aluandreg_autogen.dir/build
.PHONY : tst_aluandreg_autogen/fast

#=============================================================================
# Target rules for targets named tst_registerfile_autogen

# Build rule for target.
tst_registerfile_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_registerfile_autogen
.PHONY : tst_registerfile_autogen

# fast build rule for target.
tst_registerfile_autogen/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_registerfile_autogen.dir/build.make external/VSRTL/test/CMakeFiles/tst_registerfile_autogen.dir/build
.PHONY : tst_registerfile_autogen/fast

#=============================================================================
# Target rules for targets named tst_memory_autogen

# Build rule for target.
tst_memory_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tst_memory_autogen
.PHONY : tst_memory_autogen

# fast build rule for target.
tst_memory_autogen/fast:
	$(MAKE) -f external/VSRTL/test/CMakeFiles/tst_memory_autogen.dir/build.make external/VSRTL/test/CMakeFiles/tst_memory_autogen.dir/build
.PHONY : tst_memory_autogen/fast

#=============================================================================
# Target rules for targets named dwarf++

# Build rule for target.
dwarf++: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dwarf++
.PHONY : dwarf++

# fast build rule for target.
dwarf++/fast:
	$(MAKE) -f external/libelfin/CMakeFiles/dwarf++.dir/build.make external/libelfin/CMakeFiles/dwarf++.dir/build
.PHONY : dwarf++/fast

#=============================================================================
# Target rules for targets named elf++

# Build rule for target.
elf++: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 elf++
.PHONY : elf++

# fast build rule for target.
elf++/fast:
	$(MAKE) -f external/libelfin/CMakeFiles/elf++.dir/build.make external/libelfin/CMakeFiles/elf++.dir/build
.PHONY : elf++/fast

#=============================================================================
# Target rules for targets named dwarf++_autogen

# Build rule for target.
dwarf++_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dwarf++_autogen
.PHONY : dwarf++_autogen

# fast build rule for target.
dwarf++_autogen/fast:
	$(MAKE) -f external/libelfin/CMakeFiles/dwarf++_autogen.dir/build.make external/libelfin/CMakeFiles/dwarf++_autogen.dir/build
.PHONY : dwarf++_autogen/fast

#=============================================================================
# Target rules for targets named elf++_autogen

# Build rule for target.
elf++_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 elf++_autogen
.PHONY : elf++_autogen

# fast build rule for target.
elf++_autogen/fast:
	$(MAKE) -f external/libelfin/CMakeFiles/elf++_autogen.dir/build.make external/libelfin/CMakeFiles/elf++_autogen.dir/build
.PHONY : elf++_autogen/fast

#=============================================================================
# Target rules for targets named ripes_lib

# Build rule for target.
ripes_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ripes_lib
.PHONY : ripes_lib

# fast build rule for target.
ripes_lib/fast:
	$(MAKE) -f src/CMakeFiles/ripes_lib.dir/build.make src/CMakeFiles/ripes_lib.dir/build
.PHONY : ripes_lib/fast

#=============================================================================
# Target rules for targets named ripes_lib_autogen

# Build rule for target.
ripes_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ripes_lib_autogen
.PHONY : ripes_lib_autogen

# fast build rule for target.
ripes_lib_autogen/fast:
	$(MAKE) -f src/CMakeFiles/ripes_lib_autogen.dir/build.make src/CMakeFiles/ripes_lib_autogen.dir/build
.PHONY : ripes_lib_autogen/fast

#=============================================================================
# Target rules for targets named isa_lib

# Build rule for target.
isa_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 isa_lib
.PHONY : isa_lib

# fast build rule for target.
isa_lib/fast:
	$(MAKE) -f src/isa/CMakeFiles/isa_lib.dir/build.make src/isa/CMakeFiles/isa_lib.dir/build
.PHONY : isa_lib/fast

#=============================================================================
# Target rules for targets named isa_lib_autogen

# Build rule for target.
isa_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 isa_lib_autogen
.PHONY : isa_lib_autogen

# fast build rule for target.
isa_lib_autogen/fast:
	$(MAKE) -f src/isa/CMakeFiles/isa_lib_autogen.dir/build.make src/isa/CMakeFiles/isa_lib_autogen.dir/build
.PHONY : isa_lib_autogen/fast

#=============================================================================
# Target rules for targets named cachesim_lib

# Build rule for target.
cachesim_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cachesim_lib
.PHONY : cachesim_lib

# fast build rule for target.
cachesim_lib/fast:
	$(MAKE) -f src/cachesim/CMakeFiles/cachesim_lib.dir/build.make src/cachesim/CMakeFiles/cachesim_lib.dir/build
.PHONY : cachesim_lib/fast

#=============================================================================
# Target rules for targets named cachesim_lib_autogen

# Build rule for target.
cachesim_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cachesim_lib_autogen
.PHONY : cachesim_lib_autogen

# fast build rule for target.
cachesim_lib_autogen/fast:
	$(MAKE) -f src/cachesim/CMakeFiles/cachesim_lib_autogen.dir/build.make src/cachesim/CMakeFiles/cachesim_lib_autogen.dir/build
.PHONY : cachesim_lib_autogen/fast

#=============================================================================
# Target rules for targets named editor_lib

# Build rule for target.
editor_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 editor_lib
.PHONY : editor_lib

# fast build rule for target.
editor_lib/fast:
	$(MAKE) -f src/editor/CMakeFiles/editor_lib.dir/build.make src/editor/CMakeFiles/editor_lib.dir/build
.PHONY : editor_lib/fast

#=============================================================================
# Target rules for targets named editor_lib_autogen

# Build rule for target.
editor_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 editor_lib_autogen
.PHONY : editor_lib_autogen

# fast build rule for target.
editor_lib_autogen/fast:
	$(MAKE) -f src/editor/CMakeFiles/editor_lib_autogen.dir/build.make src/editor/CMakeFiles/editor_lib_autogen.dir/build
.PHONY : editor_lib_autogen/fast

#=============================================================================
# Target rules for targets named syscall_lib

# Build rule for target.
syscall_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 syscall_lib
.PHONY : syscall_lib

# fast build rule for target.
syscall_lib/fast:
	$(MAKE) -f src/syscall/CMakeFiles/syscall_lib.dir/build.make src/syscall/CMakeFiles/syscall_lib.dir/build
.PHONY : syscall_lib/fast

#=============================================================================
# Target rules for targets named syscall_lib_autogen

# Build rule for target.
syscall_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 syscall_lib_autogen
.PHONY : syscall_lib_autogen

# fast build rule for target.
syscall_lib_autogen/fast:
	$(MAKE) -f src/syscall/CMakeFiles/syscall_lib_autogen.dir/build.make src/syscall/CMakeFiles/syscall_lib_autogen.dir/build
.PHONY : syscall_lib_autogen/fast

#=============================================================================
# Target rules for targets named assembler_lib

# Build rule for target.
assembler_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assembler_lib
.PHONY : assembler_lib

# fast build rule for target.
assembler_lib/fast:
	$(MAKE) -f src/assembler/CMakeFiles/assembler_lib.dir/build.make src/assembler/CMakeFiles/assembler_lib.dir/build
.PHONY : assembler_lib/fast

#=============================================================================
# Target rules for targets named assembler_lib_autogen

# Build rule for target.
assembler_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assembler_lib_autogen
.PHONY : assembler_lib_autogen

# fast build rule for target.
assembler_lib_autogen/fast:
	$(MAKE) -f src/assembler/CMakeFiles/assembler_lib_autogen.dir/build.make src/assembler/CMakeFiles/assembler_lib_autogen.dir/build
.PHONY : assembler_lib_autogen/fast

#=============================================================================
# Target rules for targets named io_lib

# Build rule for target.
io_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 io_lib
.PHONY : io_lib

# fast build rule for target.
io_lib/fast:
	$(MAKE) -f src/io/CMakeFiles/io_lib.dir/build.make src/io/CMakeFiles/io_lib.dir/build
.PHONY : io_lib/fast

#=============================================================================
# Target rules for targets named io_lib_autogen

# Build rule for target.
io_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 io_lib_autogen
.PHONY : io_lib_autogen

# fast build rule for target.
io_lib_autogen/fast:
	$(MAKE) -f src/io/CMakeFiles/io_lib_autogen.dir/build.make src/io/CMakeFiles/io_lib_autogen.dir/build
.PHONY : io_lib_autogen/fast

#=============================================================================
# Target rules for targets named utilities_lib

# Build rule for target.
utilities_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utilities_lib
.PHONY : utilities_lib

# fast build rule for target.
utilities_lib/fast:
	$(MAKE) -f src/utilities/CMakeFiles/utilities_lib.dir/build.make src/utilities/CMakeFiles/utilities_lib.dir/build
.PHONY : utilities_lib/fast

#=============================================================================
# Target rules for targets named utilities_lib_autogen

# Build rule for target.
utilities_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utilities_lib_autogen
.PHONY : utilities_lib_autogen

# fast build rule for target.
utilities_lib_autogen/fast:
	$(MAKE) -f src/utilities/CMakeFiles/utilities_lib_autogen.dir/build.make src/utilities/CMakeFiles/utilities_lib_autogen.dir/build
.PHONY : utilities_lib_autogen/fast

#=============================================================================
# Target rules for targets named rv6s_dual

# Build rule for target.
rv6s_dual: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rv6s_dual
.PHONY : rv6s_dual

# fast build rule for target.
rv6s_dual/fast:
	$(MAKE) -f src/processors/CMakeFiles/rv6s_dual.dir/build.make src/processors/CMakeFiles/rv6s_dual.dir/build
.PHONY : rv6s_dual/fast

#=============================================================================
# Target rules for targets named rv5s_no_fw

# Build rule for target.
rv5s_no_fw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rv5s_no_fw
.PHONY : rv5s_no_fw

# fast build rule for target.
rv5s_no_fw/fast:
	$(MAKE) -f src/processors/CMakeFiles/rv5s_no_fw.dir/build.make src/processors/CMakeFiles/rv5s_no_fw.dir/build
.PHONY : rv5s_no_fw/fast

#=============================================================================
# Target rules for targets named rv5s_no_fw_hz

# Build rule for target.
rv5s_no_fw_hz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rv5s_no_fw_hz
.PHONY : rv5s_no_fw_hz

# fast build rule for target.
rv5s_no_fw_hz/fast:
	$(MAKE) -f src/processors/CMakeFiles/rv5s_no_fw_hz.dir/build.make src/processors/CMakeFiles/rv5s_no_fw_hz.dir/build
.PHONY : rv5s_no_fw_hz/fast

#=============================================================================
# Target rules for targets named rv5s_no_hz

# Build rule for target.
rv5s_no_hz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rv5s_no_hz
.PHONY : rv5s_no_hz

# fast build rule for target.
rv5s_no_hz/fast:
	$(MAKE) -f src/processors/CMakeFiles/rv5s_no_hz.dir/build.make src/processors/CMakeFiles/rv5s_no_hz.dir/build
.PHONY : rv5s_no_hz/fast

#=============================================================================
# Target rules for targets named rv5s

# Build rule for target.
rv5s: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rv5s
.PHONY : rv5s

# fast build rule for target.
rv5s/fast:
	$(MAKE) -f src/processors/CMakeFiles/rv5s.dir/build.make src/processors/CMakeFiles/rv5s.dir/build
.PHONY : rv5s/fast

#=============================================================================
# Target rules for targets named rvss

# Build rule for target.
rvss: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rvss
.PHONY : rvss

# fast build rule for target.
rvss/fast:
	$(MAKE) -f src/processors/CMakeFiles/rvss.dir/build.make src/processors/CMakeFiles/rvss.dir/build
.PHONY : rvss/fast

#=============================================================================
# Target rules for targets named RISC-V_lib

# Build rule for target.
RISC-V_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RISC-V_lib
.PHONY : RISC-V_lib

# fast build rule for target.
RISC-V_lib/fast:
	$(MAKE) -f src/processors/CMakeFiles/RISC-V_lib.dir/build.make src/processors/CMakeFiles/RISC-V_lib.dir/build
.PHONY : RISC-V_lib/fast

#=============================================================================
# Target rules for targets named rv6s_dual_autogen

# Build rule for target.
rv6s_dual_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rv6s_dual_autogen
.PHONY : rv6s_dual_autogen

# fast build rule for target.
rv6s_dual_autogen/fast:
	$(MAKE) -f src/processors/CMakeFiles/rv6s_dual_autogen.dir/build.make src/processors/CMakeFiles/rv6s_dual_autogen.dir/build
.PHONY : rv6s_dual_autogen/fast

#=============================================================================
# Target rules for targets named rv5s_no_fw_autogen

# Build rule for target.
rv5s_no_fw_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rv5s_no_fw_autogen
.PHONY : rv5s_no_fw_autogen

# fast build rule for target.
rv5s_no_fw_autogen/fast:
	$(MAKE) -f src/processors/CMakeFiles/rv5s_no_fw_autogen.dir/build.make src/processors/CMakeFiles/rv5s_no_fw_autogen.dir/build
.PHONY : rv5s_no_fw_autogen/fast

#=============================================================================
# Target rules for targets named rv5s_no_fw_hz_autogen

# Build rule for target.
rv5s_no_fw_hz_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rv5s_no_fw_hz_autogen
.PHONY : rv5s_no_fw_hz_autogen

# fast build rule for target.
rv5s_no_fw_hz_autogen/fast:
	$(MAKE) -f src/processors/CMakeFiles/rv5s_no_fw_hz_autogen.dir/build.make src/processors/CMakeFiles/rv5s_no_fw_hz_autogen.dir/build
.PHONY : rv5s_no_fw_hz_autogen/fast

#=============================================================================
# Target rules for targets named rv5s_no_hz_autogen

# Build rule for target.
rv5s_no_hz_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rv5s_no_hz_autogen
.PHONY : rv5s_no_hz_autogen

# fast build rule for target.
rv5s_no_hz_autogen/fast:
	$(MAKE) -f src/processors/CMakeFiles/rv5s_no_hz_autogen.dir/build.make src/processors/CMakeFiles/rv5s_no_hz_autogen.dir/build
.PHONY : rv5s_no_hz_autogen/fast

#=============================================================================
# Target rules for targets named rv5s_autogen

# Build rule for target.
rv5s_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rv5s_autogen
.PHONY : rv5s_autogen

# fast build rule for target.
rv5s_autogen/fast:
	$(MAKE) -f src/processors/CMakeFiles/rv5s_autogen.dir/build.make src/processors/CMakeFiles/rv5s_autogen.dir/build
.PHONY : rv5s_autogen/fast

#=============================================================================
# Target rules for targets named rvss_autogen

# Build rule for target.
rvss_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rvss_autogen
.PHONY : rvss_autogen

# fast build rule for target.
rvss_autogen/fast:
	$(MAKE) -f src/processors/CMakeFiles/rvss_autogen.dir/build.make src/processors/CMakeFiles/rvss_autogen.dir/build
.PHONY : rvss_autogen/fast

#=============================================================================
# Target rules for targets named RISC-V_lib_autogen

# Build rule for target.
RISC-V_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RISC-V_lib_autogen
.PHONY : RISC-V_lib_autogen

# fast build rule for target.
RISC-V_lib_autogen/fast:
	$(MAKE) -f src/processors/CMakeFiles/RISC-V_lib_autogen.dir/build.make src/processors/CMakeFiles/RISC-V_lib_autogen.dir/build
.PHONY : RISC-V_lib_autogen/fast

#=============================================================================
# Target rules for targets named version_file

# Build rule for target.
version_file: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 version_file
.PHONY : version_file

# fast build rule for target.
version_file/fast:
	$(MAKE) -f src/version/CMakeFiles/version_file.dir/build.make src/version/CMakeFiles/version_file.dir/build
.PHONY : version_file/fast

#=============================================================================
# Target rules for targets named version_lib

# Build rule for target.
version_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 version_lib
.PHONY : version_lib

# fast build rule for target.
version_lib/fast:
	$(MAKE) -f src/version/CMakeFiles/version_lib.dir/build.make src/version/CMakeFiles/version_lib.dir/build
.PHONY : version_lib/fast

#=============================================================================
# Target rules for targets named version_lib_autogen

# Build rule for target.
version_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 version_lib_autogen
.PHONY : version_lib_autogen

# fast build rule for target.
version_lib_autogen/fast:
	$(MAKE) -f src/version/CMakeFiles/version_lib_autogen.dir/build.make src/version/CMakeFiles/version_lib_autogen.dir/build
.PHONY : version_lib_autogen/fast

Ripes_autogen/mocs_compilation.o: Ripes_autogen/mocs_compilation.cpp.o

.PHONY : Ripes_autogen/mocs_compilation.o

# target to build an object file
Ripes_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/Ripes_autogen/mocs_compilation.cpp.o
.PHONY : Ripes_autogen/mocs_compilation.cpp.o

Ripes_autogen/mocs_compilation.i: Ripes_autogen/mocs_compilation.cpp.i

.PHONY : Ripes_autogen/mocs_compilation.i

# target to preprocess a source file
Ripes_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/Ripes_autogen/mocs_compilation.cpp.i
.PHONY : Ripes_autogen/mocs_compilation.cpp.i

Ripes_autogen/mocs_compilation.s: Ripes_autogen/mocs_compilation.cpp.s

.PHONY : Ripes_autogen/mocs_compilation.s

# target to generate assembly for a file
Ripes_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/Ripes_autogen/mocs_compilation.cpp.s
.PHONY : Ripes_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/main.cpp.s
.PHONY : main.cpp.s

qrc_examples.o: qrc_examples.cpp.o

.PHONY : qrc_examples.o

# target to build an object file
qrc_examples.cpp.o:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/qrc_examples.cpp.o
.PHONY : qrc_examples.cpp.o

qrc_examples.i: qrc_examples.cpp.i

.PHONY : qrc_examples.i

# target to preprocess a source file
qrc_examples.cpp.i:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/qrc_examples.cpp.i
.PHONY : qrc_examples.cpp.i

qrc_examples.s: qrc_examples.cpp.s

.PHONY : qrc_examples.s

# target to generate assembly for a file
qrc_examples.cpp.s:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/qrc_examples.cpp.s
.PHONY : qrc_examples.cpp.s

qrc_fonts.o: qrc_fonts.cpp.o

.PHONY : qrc_fonts.o

# target to build an object file
qrc_fonts.cpp.o:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/qrc_fonts.cpp.o
.PHONY : qrc_fonts.cpp.o

qrc_fonts.i: qrc_fonts.cpp.i

.PHONY : qrc_fonts.i

# target to preprocess a source file
qrc_fonts.cpp.i:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/qrc_fonts.cpp.i
.PHONY : qrc_fonts.cpp.i

qrc_fonts.s: qrc_fonts.cpp.s

.PHONY : qrc_fonts.s

# target to generate assembly for a file
qrc_fonts.cpp.s:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/qrc_fonts.cpp.s
.PHONY : qrc_fonts.cpp.s

qrc_icons.o: qrc_icons.cpp.o

.PHONY : qrc_icons.o

# target to build an object file
qrc_icons.cpp.o:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/qrc_icons.cpp.o
.PHONY : qrc_icons.cpp.o

qrc_icons.i: qrc_icons.cpp.i

.PHONY : qrc_icons.i

# target to preprocess a source file
qrc_icons.cpp.i:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/qrc_icons.cpp.i
.PHONY : qrc_icons.cpp.i

qrc_icons.s: qrc_icons.cpp.s

.PHONY : qrc_icons.s

# target to generate assembly for a file
qrc_icons.cpp.s:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/qrc_icons.cpp.s
.PHONY : qrc_icons.cpp.s

qrc_layouts.o: qrc_layouts.cpp.o

.PHONY : qrc_layouts.o

# target to build an object file
qrc_layouts.cpp.o:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/qrc_layouts.cpp.o
.PHONY : qrc_layouts.cpp.o

qrc_layouts.i: qrc_layouts.cpp.i

.PHONY : qrc_layouts.i

# target to preprocess a source file
qrc_layouts.cpp.i:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/qrc_layouts.cpp.i
.PHONY : qrc_layouts.cpp.i

qrc_layouts.s: qrc_layouts.cpp.s

.PHONY : qrc_layouts.s

# target to generate assembly for a file
qrc_layouts.cpp.s:
	$(MAKE) -f CMakeFiles/Ripes.dir/build.make CMakeFiles/Ripes.dir/qrc_layouts.cpp.s
.PHONY : qrc_layouts.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... Ripes"
	@echo "... Ripes_autogen"
	@echo "... fancytabbar_lib"
	@echo "... fancytabbar_lib_autogen"
	@echo "... VSRTL"
	@echo "... VSRTL_autogen"
	@echo "... vsrtl_int_lib"
	@echo "... vsrtl_int_lib_autogen"
	@echo "... vsrtl_core_lib"
	@echo "... vsrtl_core_lib_autogen"
	@echo "... vsrtl_gfx_lib"
	@echo "... vsrtl_gfx_lib_autogen"
	@echo "... vsrtl_cmp_lib"
	@echo "... vsrtl_cmp_lib_autogen"
	@echo "... SingleCycleLeros"
	@echo "... SingleCycleLeros_autogen"
	@echo "... tst_nestedcomponent"
	@echo "... tst_leros"
	@echo "... tst_adderandreg"
	@echo "... tst_counter"
	@echo "... tst_rannumgen"
	@echo "... tst_enumandmux"
	@echo "... tst_aluandreg"
	@echo "... tst_registerfile"
	@echo "... tst_memory"
	@echo "... tst_nestedcomponent_autogen"
	@echo "... tst_leros_autogen"
	@echo "... tst_adderandreg_autogen"
	@echo "... tst_counter_autogen"
	@echo "... tst_rannumgen_autogen"
	@echo "... tst_enumandmux_autogen"
	@echo "... tst_aluandreg_autogen"
	@echo "... tst_registerfile_autogen"
	@echo "... tst_memory_autogen"
	@echo "... dwarf++"
	@echo "... elf++"
	@echo "... dwarf++_autogen"
	@echo "... elf++_autogen"
	@echo "... ripes_lib"
	@echo "... ripes_lib_autogen"
	@echo "... isa_lib"
	@echo "... isa_lib_autogen"
	@echo "... cachesim_lib"
	@echo "... cachesim_lib_autogen"
	@echo "... editor_lib"
	@echo "... editor_lib_autogen"
	@echo "... syscall_lib"
	@echo "... syscall_lib_autogen"
	@echo "... assembler_lib"
	@echo "... assembler_lib_autogen"
	@echo "... io_lib"
	@echo "... io_lib_autogen"
	@echo "... utilities_lib"
	@echo "... utilities_lib_autogen"
	@echo "... rv6s_dual"
	@echo "... rv5s_no_fw"
	@echo "... rv5s_no_fw_hz"
	@echo "... rv5s_no_hz"
	@echo "... rv5s"
	@echo "... rvss"
	@echo "... RISC-V_lib"
	@echo "... rv6s_dual_autogen"
	@echo "... rv5s_no_fw_autogen"
	@echo "... rv5s_no_fw_hz_autogen"
	@echo "... rv5s_no_hz_autogen"
	@echo "... rv5s_autogen"
	@echo "... rvss_autogen"
	@echo "... RISC-V_lib_autogen"
	@echo "... version_file"
	@echo "... version_lib"
	@echo "... version_lib_autogen"
	@echo "... Ripes_autogen/mocs_compilation.o"
	@echo "... Ripes_autogen/mocs_compilation.i"
	@echo "... Ripes_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... qrc_examples.o"
	@echo "... qrc_examples.i"
	@echo "... qrc_examples.s"
	@echo "... qrc_fonts.o"
	@echo "... qrc_fonts.i"
	@echo "... qrc_fonts.s"
	@echo "... qrc_icons.o"
	@echo "... qrc_icons.i"
	@echo "... qrc_icons.s"
	@echo "... qrc_layouts.o"
	@echo "... qrc_layouts.i"
	@echo "... qrc_layouts.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

